---
# Playbook to provision instances on osp

- hosts: localhost
  vars:
    OSP_GUID: f3be
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- hosts: workstation
  become: yes
  roles:
    - osp-instances
